server:
  port: 6010

spring:
  application:
    name: appgateway

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders: "*"

          routes:

            - id: usuarios-service
              uri: http://localhost:8082
              predicates:
                - Path=/usuarios/**
              filters:
                - StripPrefix=1

            - id: productos-service
              uri: http://localhost:8083
              predicates:
                - Path=/productos/**
              filters:
                - StripPrefix=1

            - id: ventas-service
              uri: http://localhost:8084
              predicates:
                - Path=/ventas/**
              filters:
                - StripPrefix=1

            - id: pagos-service
              uri: http://localhost:8085
              predicates:
                - Path=/pagos/**
              filters:
                - StripPrefix=1