version: "1"

services:
   broker:
    image: johnnypark/kafka-zookeeper:2.6.0
    container_name: service-broker
    restart: always
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
    - ADVERTISED_HOST=127.0.0.1
    - NUM_PARTITIONS=10
    networks:
    - td2026
    
networks:
  td2026:
    name: ms-unu

